apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: rabbitmq
  name: notification-mq-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: rabbitmq
    spec:
      containers:
      - image: rabbitmq
        name: rabbitmq
        ports:
        - containerPort: 5672
        resources:
          limits:
            cpu: 100m
