apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: notification-db
  name: notification-db-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: notification-db
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
            - name: mongo-persistent-storage
              mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          gcePersistentDisk:
            pdName: notification-db-disk
            fsType: ext4
